const brandsData: Brand[] = [
  {
    id: 1,
    name: 'Formbold',
    href: '#',
    image: '/images/brands/formbold.svg',
    imageLight: '/images/brands/formbold-light.svg',
    featureLogo: '/images/feature-images/feature-1.png',
  },
  {
    id: 2,
    name: 'UIdeck',
    href: '#',
    image: '/images/brands/uideck.svg',
    imageLight: '/images/brands/uideck-light.svg',
    featureLogo: '/images/feature-images/feature-2.png',
  },
  {
    id: 3,
    name: 'Tailgrids',
    href: '#',
    image: '/images/brands/tailgrids.svg',
    imageLight: '/images/brands/tailgrids-light.svg',
    featureLogo: '/images/feature-images/feature-3.png',
  },
  {
    id: 4,
    name: 'Lineicons',
    href: '#',
    image: '/images/brands/lineicons.svg',
    imageLight: '/images/brands/lineicons-light.svg',
    featureLogo: '/images/feature-images/feature-4.svg',
  },
  {
    id: 5,
    name: 'Tailadmin',
    href: '#',
    image: '/images/brands/tailadmin.svg',
    imageLight: '/images/brands/tailadmin-light.svg',
    featureLogo: '/images/feature-images/feature-5.png',
  },
  {
    id: 6,
    name: 'PlainAdmin',
    href: '#',
    image: '/images/brands/plainadmin.svg',
    imageLight: '/images/brands/plainadmin-light.svg',
    featureLogo: '/images/feature-images/feature-6.webp',
  },
  {
    id: 7,
    name: 'PlainAdmin',
    href: '#',
    image: '/images/brands/plainadmin.svg',
    imageLight: '/images/brands/plainadmin-light.svg',
    featureLogo: '/images/feature-images/feature-7.jpeg',
  },
  {
    id: 8,
    name: 'PlainAdmin',
    href: '#',
    image: '/images/brands/plainadmin.svg',
    imageLight: '/images/brands/plainadmin-light.svg',
    featureLogo: '/images/feature-images/feature-8.svg',
  },
];

export default brandsData;
